# Generated by Django 4.2.2 on 2023-07-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentario',
            table='comentario',
        ),
    ]
