# Generated by Django 4.2.2 on 2023-06-22 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0002_publicacion_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='visitas',
            field=models.ManyToManyField(blank=True, related_name='visitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_calle', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_depto', models.CharField(blank=True, max_length=5, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField()),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.publicacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
