# Generated by Django 4.2.2 on 2023-06-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_publicacion_visitas_perfil_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='visitas',
        ),
    ]
