# Generated by Django 4.2.2 on 2023-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(db_index=True, default='0000000000', max_length=10),
        ),
    ]
